# This is a basic workflow to help you get started with Actions

name: deploy to http://124.70.83.234:8088

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
      - name: 获取项目
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: 代码打包
        run: |
          git pull
          yarn
          yarn build
      - name: 发布
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.DR_HOST }}
          user: ${{ secrets.DR_USERNAME }}
          pass: ${{ secrets.DR_PASSWORD }}
          connect_timeout: 10s
          local: "./docs/.vuepress/dist/*" # 这里是下一步要创建的vue项目构建完成后的静态资源路径
          remote: /root/projects/learndocs-vuepress2/docs/.vuepress/dist # 这里是 step1 中，在服务器上创建用于存放静态资源的文件夹
