# This is a basic workflow to help you get started with Actions

name: deploy to http://124.70.83.234:8088

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Run a multi-line script
        run: |
          # cd /learndocs-vuepress2
          yarn
          yarn build
      - name: deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.DR_HOST }}
          user: ${{ secrets.DR_USERNAME }}
          pass: ${{ secrets.DR_PASSWORD }}
          connect_timeout: 10s
